### PR TITLE
Update User Guide

### PR DESCRIPTION
**Pull request by Zxun2**

### CODE REVIEW

**Comment by wz2k** [comment]
🤔

**Comment by zhacatomn** [comment]
As opposed to having a new table just for the icons, I wonder if you might consider something like this, where the icon is next to the header:
image

The code for this is:
```markdown
### <img src="images/userGuide/icons/tags.png" width="20" style="vertical-align: middle"/> Tags
```

**Comment by Zxun2** [comment]
> As opposed to having a new table just for the icons, I wonder if you might consider something like this, where the icon is next to the header: image
> 
> The code for this is:
> 
> ```gfm
> ###  Tags
> ```

Great idea!

**Review by gohyongjing — APPROVED** [review]
LGTM 👍

**Pull request closed without merging**
